dist: xenial
git:
  quiet: true
  depth: 1
notifications:
  email: false
language: java
jdk: openjdk8
python: 3
node_js: lts/*
install: true
env:
  global:
    - TERM=dumb
addons:
  apt:
    update: true
    packages:
      - jq
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - python3-dev
      - python3-pip
      - python3-six
      - python3-setuptools
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
  - pip install --user $(whoami) --upgrade httpie >/dev/null 2>&1
  - http --version --debug
  #
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 5432 5672 27017 8080 8000 8081 80 80
jobs:
  include:
    - stage: openjdk8
      jdk: openjdk8
      name: "maven tests"
      before_script: for i in ${PROJECTS} ; do cp -Rfv $TRAVIS_BUILD_DIR/$i/src/test/resources/logback-maven.xml $TRAVIS_BUILD_DIR/$i/src/test/resources/logback.xml ; done
      script: cd $TRAVIS_BUILD_DIR && ./mvnw clean test
    - stage: openjdk8
      jdk: openjdk8
      name: "maven updates"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
    - stage: openjdk8
      jdk: openjdk8
      name: "gradle tests"
      before_script: for i in ${PROJECTS} ; do cp -Rfv $TRAVIS_BUILD_DIR/$i/src/test/resources/logback-gradle.xml $TRAVIS_BUILD_DIR/$i/src/test/resources/logback.xml ; done
      script: cd $TRAVIS_BUILD_DIR && ./gradlew clean test
    - stage: openjdk8
      jdk: openjdk8
      name: "gradle updates"
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
      after_script: cat $TRAVIS_BUILD_DIR/build/dependencyUpdates/report.txt
cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - node_modules
    - ~/.gradle
    - ~/.ivy
    - ~/.sbt
    - ~/.m2
  pip: true
  npm: true
  packages: true
before_deploy:
  - npm i ; npm run gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ./.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
